<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxGIFQg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxGIFQg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxGIFQg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxGIFQg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAxGIFQg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AxGIFQg',
    'container.build_id' => '7cbc966a',
    'container.build_time' => 1570708938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxGIFQg');
